# Generated by Django 6.0.5 on 2026-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='categorylimit',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
