# Generated by Django 6.0.5 on 2026-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_budgetrecord_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.CharField(choices=[('NEED', 'Need'), ('WANT', 'Want'), ('SAVING', 'Saving'), ('INCOME', 'Income')], max_length=20),
        ),
    ]
