# Generated by Django 6.0.5 on 2026-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_challenge_userchallengeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
